(define exit? false)
(define text-window (struct 'buffer (new-buffer "") 'cursor 0))
(define windows (list text-window))

(define (handle-event! event)
    (when (= event "<esc>")
      (define exit? true)
      (return))
  (when (= event "<backspace>")
    (when (< 0 (struct-get text-window 'cursor))
      (struct-set! text-window 'cursor (- (struct-get text-window 'cursor) 1))
      (buffer-delete! (struct-get text-window 'buffer)
                      (struct-get text-window 'cursor)))
    (return))
  (when (= event "<left>")
    (struct-set! text-window 'cursor (buffer-normalize-cursor (struct-get text-window 'buffer)
                                                              (- (struct-get text-window 'cursor) 1)))
    (return))
  (when (= event "<right>")
    (struct-set! text-window 'cursor (buffer-normalize-cursor text-buffer (+ (struct-get text-window 'cursor) 1)))
    (return))
  (when (= event "<enter>")
    (struct-set! text-window
                 'cursor
                 (+ (struct-get text-window 'cursor)
                    (buffer-insert! (struct-get text-window 'buffer)
                                    (struct-get text-window 'cursor)
                                    "
")))
    (return))
  (struct-set! text-window
               'cursor
               (+ (struct-get text-window 'cursor)
                  (buffer-insert! (struct-get text-window 'buffer)
                                  (struct-get text-window 'cursor) event))))
