#+TITLE: Built-Ins
#+AUTHOR: Will Medrano

* Modules
:PROPERTIES:
:CUSTOM_ID: Modules-xay5olk0z8k0
:END:

Modules are created by storing ~spore~ code in a file. The file can
then be loaded at runtime to provide functionality. Items in the
module can be referenced with the syntax ~<module-alias>/<symbol>~
where ~module-alias~ is the name of the file stripped of its file
extension and ~<symbol>~ is any item defined in the module.

Example file: ~"/tmp/shapes.spore"~

#+BEGIN_SRC lisp
(define pi 3.14159)
(define (circle-area radius)
  (* pi radius radius))
#+END_SRC

Repl interaction:

#+BEGIN_SRC lisp
(import "/tmp/shapes.spore") ;; Imported under the shapes/ prefix.
shapes/pi ;; 3.14159
(circle-area 2) ;; 12.56636
#+END_SRC

* Numbers
:PROPERTIES:
:CUSTOM_ID: Numbers-xan1fsa0e7k0
:END:

Numbers are a fundamental data type supporting both integers and
floating-point values. Spore provides a variety of arithmetic and
comparison operations to manipulate numbers.

** Arithmetic
:PROPERTIES:
:CUSTOM_ID: NumbersArithmetic-05tedsa0e7k0
:END:

*** Addition (+)
:PROPERTIES:
:CUSTOM_ID: NumbersArithmeticAddition-r5i5vxa0e7k0
:END:

Adds multiple numbers together.

#+BEGIN_SRC lisp
  (+)         ;; 0
  (+ 1 2 3 4) ;; 10
  (+ 1.1 2.3) ;; 3.4
#+END_SRC

*** Subtraction (-)
:PROPERTIES:
:CUSTOM_ID: NumbersArithmeticSubtraction-mn0ly5b0e7k0
:END:

Subtracts subsequent numbers from the first number. If only a single
number is provided, then it is negated.

#+BEGIN_SRC lisp
  (-)           ;; <error>
  (- 1)         ;; -1
  (- 1 10)      ;; -9
  (- 0 1 2 3 4) ;; -10
#+END_SRC

*** Multiplication (*)
:PROPERTIES:
:CUSTOM_ID: NumbersArithmeticMultiplication-qz2ly5b0e7k0
:END:

Multiplies multiple numbers together.

#+BEGIN_SRC lisp
  (*)       ;; 0
  (* 2 3)   ;; 6
  (* 2 3 4) ;; 24
#+END_SRC

*** Division (/)
:PROPERTIES:
:CUSTOM_ID: NumbersArithmeticDivision-s45ly5b0e7k0
:END:

Divide the first number by subsequent arguments. If only one argument
is provided, then the reciprocal is returned.

#+BEGIN_SRC lisp
  (/)       ;; <error>
  (/ 2)     ;; 0.5
  (/ 3 4)   ;; 0.75
  (/ 3 2 4) ;; 0.375
#+END_SRC

*** Comparison
:PROPERTIES:
:CUSTOM_ID: NumbersArithmeticComparison-7d3g4fb0e7k0
:END:

Numbers can be compared with ~<~, ~<=~, ~>~, ~>=~, and ~equal?~.

#+BEGIN_SRC lisp
  (< 1 2)      ;; true
  (<= 1 1)     ;; true
  (> 2 1)      ;; true
  (>= 2 2)     ;; true
  (equal? 1 1) ;; true
  (equal? 1 2) ;; false
#+END_SRC

* Strings
:PROPERTIES:
:CUSTOM_ID: Strings-ofnh9sa0e7k0
:END:

Strings in Spore are sequences of characters. They support a variety
of operations for manipulation and comparison.

Spore strings are delimited by double quotes ~"~. To include a double
quote character within a string, use the escape sequence ~\"~.


*Examples*
- ~"This is a string"~
- ~"This string contains a quote: \"Hello!\""~

** Operations
:PROPERTIES:
:CUSTOM_ID: StringsOperations-lrw2ltc0e7k0
:END:

*** equal?
:PROPERTIES:
:CUSTOM_ID: StringsOperationsequal-7md599t0z8k0
:END:

~equal?~ compares two strings for equality.

#+BEGIN_SRC lisp
  (equal? "bat" "bat") ;; true
  (equal? "bat" "tab") ;; false
  (equal? "33"  33)    ;; false
#+END_SRC


*** len
:PROPERTIES:
:CUSTOM_ID: StringsOperationslen-huy2ltc0e7k0
:END:

~len~ returns the length of a string.

#+BEGIN_SRC lisp
  (len "")       ;; 0
  (len "string") ;; 6
#+END_SRC

*** substring
:PROPERTIES:
:CUSTOM_ID: StringsOperationssubstring-5sc5twc0e7k0
:END:

~substring~ extracts a portion of a string, taking start (inclusive)
and end (exclusive) indices. The first character in the string has
index 0, and the last character has index ~(- (len <string>) 1)~.

#+BEGIN_SRC lisp
  (substring "string" 1 3)              ;; "tr"
  (substring "string" 0 (len "string")) ;; "string"
#+END_SRC

*** string-concat
:PROPERTIES:
:CUSTOM_ID: StringsOperationsstringconcat-zwg3n9k0e7k0
:END:

~string-concat~ combines (concatenates) strings into a new string.

#+BEGIN_SRC lisp
  (string-concat)                      ;; ""
  (string-concat "Hello" " " "World!") ;; "Hello World!"
#+END_SRC

* Lists
:PROPERTIES:
:CUSTOM_ID: Lists-3lqi7sa0e7k0
:END:

Lists are a fundamental data structure for organizing multiple
elements in a specific order. In Spore, lists can contain elements of
any data type, including other lists.

** Operations
:PROPERTIES:
:CUSTOM_ID: ListsOperations-o09233d0e7k0
:END:

*** list
:PROPERTIES:
:CUSTOM_ID: ListsOperationslist-nze233d0e7k0
:END:

The ~list~ procedure creates a new list from the arguments.

#+BEGIN_SRC lisp
  (list 1 2 3 4)        ;; (1 2 3 4)
  (list 1 2 (list 3 4)) ;; (1 2 (3 4))
#+END_SRC

*** list?
:PROPERTIES:
:CUSTOM_ID: ListsOperationslist-50hdso71e7k0
:END:

The ~list?~ procedure  returns ~true~ if the argument is a list, and
~false~ otherwise.

#+BEGIN_SRC lisp
  (list? (list 1 2 3)) ;; true
  (list? 1)            ;; false
#+END_SRC


*** len
:PROPERTIES:
:CUSTOM_ID: ListsOperationslen-d4c294d0e7k0
:END:

The ~len~ procedure returns the number of elements in a list.

#+BEGIN_SRC lisp
  (len (list 1 2))            ;; 2
  (len (list))                ;; 0
  (len (list 1 (list 2 3 4))) ;; 2
#+END_SRC


*** first
:PROPERTIES:
:CUSTOM_ID: ListsOperationsfirst-ox683cm0e7k0
:END:

The ~first~ procedure  returns the first element of a list.

#+BEGIN_SRC lisp
  (first (list 1 2 3)) ;; 1
  (first (list))       ;; <error>
#+END_SRC


*** rest
:PROPERTIES:
:CUSTOM_ID: ListsOperationsrest-in88zr71e7k0
:END:

The ~rest~ procedure returns a list containing all but the first
element of a list. If the list is empty, then an error is raised.

#+BEGIN_SRC lisp
  (rest (list "0" "1" "2")) ;; ("1" "2")
  (rest (list "0"))         ;; ()
  (rest (list))             ;; <error>
#+END_SRC

*** nth
:PROPERTIES:
:CUSTOM_ID: ListsOperationsnth-azohu8t0z8k0
:END:

~nth~ returns the ~nth~ element of the ~list~.

#+BEGIN_SRC lisp
  (nth (list "0" "1" "2") 0) ;; "0"
  (nth (list "0" "1" "2") 1) ;; "1"
  (nth (list "0" "1" "2") 2) ;; "2"
  (nth (list "0" "1" "2") 3) ;; <error>
#+END_SRC


* Misc
:PROPERTIES:
:CUSTOM_ID: Misc-3g1ah5a0e7k0
:END:

** do
:PROPERTIES:
:CUSTOM_ID: Miscdo-zxbl4sa0e7k0
:END:

~do~ takes any number of arguments and returns the last value.

#+BEGIN_SRC lisp
  (do 1 2 3) ;; 3
  (do)       ;; <void>
#+END_SRC

** modules
:PROPERTIES:
:CUSTOM_ID: Miscmodules-gvu1agk0z8k0
:END:

~modules~ returns all loaded modules by name as a list of strings.

#+BEGIN_SRC lisp
  (modules) ;; ("%global%" "%virtual%/repl")
#+END_SRC

** list-imports
:PROPERTIES:
:CUSTOM_ID: Misclistimports-c1y4k3u0z8k0
:END:

~list-imports~ returns the list of modules that have been imported into the
given module.

#+BEGIN_SRC lisp
  (list-imports "%global%") ;; ()
#+END_SRC

Repl loading module example:

#+BEGIN_SRC lisp
  (import "path/to/my/module.spore")
  (list-imports "%virtual%/repl") ;; ("module")
#+END_SRC
