name: test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Cargo Nextest
        uses: taiki-e/install-action@nextest
      - name: Install Cargo LLVM Cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Install LLVM Tools
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - name: Lint
        run: cargo clippy
      - name: Build
        run: cargo build --verbose --all-targets
      - name: Test
        run: |
          cargo llvm-cov nextest --no-fail-fast
          echo To create and open an HTML report locally, run:
          echo "    cargo llvm-cov nextest --open"
      - name: Doc Tests
        run: cargo doc && cargo test --doc
      - name: Run Examples
        run: cargo run --example fib
